name: tiktok_clone
description: A TikTok clone built with Flutter and Laravel backend.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  file_picker: ^8.0.0+1
  image_picker: ^1.0.7
  video_player: ^2.8.1
  mime: ^1.0.6
  photo_view: ^0.14.0 
  flutter_staggered_grid_view: ^0.7.0  # Masonry layout
  cached_network_image: ^3.3.0         # Image caching

  supabase_flutter: ^2.0.0
  cupertino_icons: ^1.0.2
  http_parser: ^4.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
# Add these dependencies to your pubspec.yaml file



# Platform-specific configurations
flutter:
  uses-material-design: true
  
  # Add these permissions to android/app/src/main/AndroidManifest.xml
  # <uses-permission android:name="android.permission.INTERNET" />
  # <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
  # <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
  # <uses-permission android:name="android.permission.CAMERA" />
  
  # Add these to ios/Runner/Info.plist
  # <key>NSCameraUsageDescription</key>
  # <string>This app needs access to camera to take photos and videos</string>
  # <key>NSPhotoLibraryUsageDescription</key>
  # <string>This app needs access to photo library to select media</string>
  # <key>NSMicrophoneUsageDescription</key>
  # <string>This app needs access to microphone to record videos</string>
